services:
  openmemory-mcp:
    image: mem0/openmemory-mcp
    build: api/
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - OPENAI_EMBEDDING_MODEL=${OPENAI_EMBEDDING_MODEL}
      - OPENAI_API_MODEL=${OPENAI_API_MODEL}
      - USER=${USER}
      - MILVUS_HOST=${MILVUS_HOST:-openmemory-milvus}
      - MILVUS_PORT=${MILVUS_PORT:-19530}
      - MILVUS_TOKEN=${MILVUS_TOKEN}
    ports:
      - "8765:8765"
    volumes:
      - openmemory_db:/usr/src/openmemory
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8765 --reload --workers 4"
    networks:
      - mem0_network

  openmemory-ui:
    build:
      context: ui/
      dockerfile: Dockerfile
    image: mem0/openmemory-ui:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_USER_ID=${USER}
    networks:
      - mem0_network

volumes:
  openmemory_db: 
    driver_opts:
      type: none
      o: bind
      device: /opt/openmemory

networks:
  mem0_network:
    driver: bridge